config/routes.rb
Rails.application.routes.draw do
  resources :photos, only: [:index, :create]
  root 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  require 'flickraw'
  before_action :set_flickr

  def index
    if !params[:user_id].nil?
      @photos = flickr.photos.search(user_id: params[:user_id]).first(15)
      @section_message = "You can see the recent photos uploaded by the user with the ID `#{params[:user_id]}` : (refresh page for updates)" # rubocop: disable Layout/LineLength
    else
      @photos = flickr.photos.getRecent.first(15)
      @section_message = 'You can see the recent photos uploaded on Flickr below: (refresh page for updates)'
    end
  rescue FlickRaw::FailedResponse => e
    p e
    redirect_to root_path, notice: 'User does not exist!'
  end

  def create
    if params[:user_id].size.positive?
      redirect_to root_path(user_id: params[:user_id])
    else
      redirect_to root_path, notice: 'Please provide a correct user id!'
    end
  end

  private

  def set_flickr
    FlickRaw.api_key = ENV['FLICKRAW_API_KEY']
    FlickRaw.shared_secret = ENV['FLICKRAW_SHARED_SECRET']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flickr Search API</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <nav class="navbar bg-primary">
      <ul class="list-unstyled navbar-left mb-0">
        <li class="navbar-brand text-white"><i class="fab fa-flickr"></i> <%= link_to 'Flicker API', root_path, class: 'font-weight-bold  text-white' %></li>
      </ul>

      <ul class="list-unstyled navbar-right mb-0">
        <li class="navbar-item"><%= link_to 'Back', root_path, class: 'btn btn-secondary' %></li>
      </ul>
    </nav>
    <% if notice %>
      <p class="notice bg-danger text-white text-center font-weight-bold py-2"><%= notice %></p>
    <% end %>
    
    <div class="container-fluid py-3 text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/index.html.erb
<main class="mx-auto my-5">
  <h1 class="">Welcome to the Flickr search API</h1>
  <%= @info %>

  <div class="search-section border-left border-right shadow rounded mx-auto my-5 p-3">
    <div class="flex-container d-flex justify-content-center align-items-center ">
      <%= form_with(method: :post, url: photos_path, local: true, class: 'search-form m-4') do |f| %>
        <%= f.text_field :user_id, class: 'p-2 h5 w-100' %> <br>
        <%= f.submit 'Search', class: 'p-2 h5 btn btn-primary w-100' %>
      <% end %>

      <div class="demo-links-container">
        <h3>Random demo users</h3>
        <ul class="demo-links list-unstyled">
          <li class="demo-link"><%= link_to 'Cristian Ceamatu', root_path(user_id: '190280325@N08') %></li>
          <li class="demo-link"><%= link_to 'Tina Sosna', root_path(user_id: 'worteinbildern') %></li>
          <li class="demo-link"><%= link_to 'Mario Calma', root_path(user_id: '134378250@N05') %></li>
          <li class="demo-link"><%= link_to 'Alessandra Marrapese', root_path(user_id: 'alessandra-photos') %></li>
          <li class="demo-link"><%= link_to 'Marta Bevacqua', root_path(user_id: 'martabevacqua') %></li>
        </ul>
      </div>
    </div>
    <p class="text-muted mt-3 mb-0 pb-0">Where to find the ID? example: https://www.flickr.com/photos/<b>you-can-find-id`s-here</b>/</p>
  </div>


  <section class="container-fluid py-4 mt-5">
      <p class="h3 mb-4"><%= @section_message %></p>
      <div class="photos-container d-inline-flex flex-wrap align-items-stretch">
      <ul class="photo-list list-unstyled">
        <li>
          <% @photos.each do |photo| %>
              <img src=<%= "http://farm#{photo.farm}.staticflickr.com/#{photo.server}/#{photo.id}_#{photo.secret}.jpg" %> alt=<%= photo.title %> class="my-3" >
          <% end %>
        </li>
      </ul>
    </div>
  </section>
</main>